#!/usr/bin/env python3
"""Atrapa launchctl: bootstrap uruchamia ProgramArguments z plisty, bootout go zabija, print
podaje pid. Stan w $FAKE_LAUNCHCTL_DB."""
import json
import os
import plistlib
import signal
import subprocess
import sys
import time

db_path = os.environ["FAKE_LAUNCHCTL_DB"]
db = json.load(open(db_path)) if os.path.exists(db_path) else {}


def save():
    json.dump(db, open(db_path, "w"))


def alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


cmd = sys.argv[1]
if cmd == "bootstrap":
    with open(sys.argv[3], "rb") as f:
        plist = plistlib.load(f)
    env = dict(os.environ, **plist.get("EnvironmentVariables", {}))
    out = open(plist["StandardErrorPath"], "ab")
    proc = subprocess.Popen(plist["ProgramArguments"], env=env, stdout=out, stderr=out, start_new_session=True)
    db[plist["Label"]] = proc.pid
    save()
elif cmd == "bootout":
    target = sys.argv[2].split("/", 2)[-1]
    pid = db.pop(target, None)
    save()
    if pid is None:
        sys.exit(3)
    try:
        os.killpg(pid, signal.SIGTERM)
    except OSError:
        pass
    for _ in range(50):
        if not alive(pid):
            break
        time.sleep(0.1)
elif cmd == "print":
    pid = db.get(sys.argv[2].split("/", 2)[-1])
    if not pid or not alive(pid):
        sys.exit(113)
    print(f"state = running\n\tpid = {pid}")
